### PR TITLE
Add tests for #175 (race condition dead awaits)

### PR DESCRIPTION
**Pull request by zapu**
Add tests for https://github.com/maxtaco/coffee-script/issues/175

### CODE REVIEW

**Comment by maxtaco** [comment]
Can you change package.json to require `iced-runtime-3` @ `3.0.4` and up?  If so then :+1:

**Comment by zapu** [comment]
I've also committed my an alternative fix, if anyone's curious:  https://github.com/zapu/coffeescript/commit/42bd5fa4ac7941793fb2ca39b18113734658c809

**Comment by maxtaco** [comment]
:+1:

**Comment by zapu** [comment]
So do you think this is ready to merge?

**Comment by zapu** [comment]
Thanks!

**Pull request merged**
