### PR TITLE
Travis CI integration

### PR DESCRIPTION
**Pull request by zapu**
Mainly for looking for regressions in older node versions.  Unsure how far we should go with these, we are already failing on <5.10, IIRC (mainline coffee fails as well).

### CODE REVIEW

**Comment by maxtaco** [comment]
👍 (will wait for CI before merge)

**Comment by maxtaco** [comment]
Great idea btw to hook up travis

**Comment by zapu** [comment]
There are a couple of tests that fail on older versions, now that CI is in place I will work on fixing them. The REPL test is kind of weird because I cannot reproduce it manually in node REPL, but maybe I'm doing something wrong.

**Comment by zapu** [comment]
Oh, got it:

```
» node --version
v4.0.0
» iced3
iced> 
iced> 
iced> 

» node --version
v6.7.0
» node ./bin/coffee
iced> 
Expression assignment to _ now disabled.
undefined
iced> 
undefined
iced> 
```

I remember reporting it long time ago in mainline coffee but no one seemed to care ;)

**Comment by zapu** [comment]
@maxtaco can we merge this? The remaining failing test is because of a bug in coffeescript ES6 module functionality. 

They are testing that exporting anonymous classes should be forbidden, but it is in fact not forbidden anywhere and will compile just fine - the test only passes because the resulting code fails because ES6 modules are not supported in Node.js. It was only exposed because the error message regarding this unimplemented feature has changed in Node 5.

**Comment by zapu** [comment]
@maxtaco ping again :) 

the other failing test on old node version was also fixed by coffeescript mainline, after this gets merged I can also pull the latest coffee, as it also got some fixes for new node release.

**Comment by maxtaco** [comment]
Thanks @zapu !!!

**Comment by zapu** [comment]
Would you have a moment to share how you did this merge? Does Github now do the merge-squash commit when you press "Merge pull request" or did start doing this by hand? Just curious :) Thanks

**Comment by maxtaco** [comment]
Great new Github feature: https://github.com/blog/2141-squash-your-commits

**Pull request merged**
