### PR TITLE
Merging coffee-script 1.11 release

### PR DESCRIPTION
**Pull request by zapu**
Biggest change is import/export syntax from ES6. Important to note is that coffee/iced does not do any module resolving, it will just emit correct JavaScript import/export code.

All tests pass, but I haven't get a chance to try all the new features. Import/export seems to work though (compiles fine). It won't work in when ran in node, because node itself does not support ES6 modules.

A relatively big pull request, because it includes all coffeescript compiles. Iced compilation output files are not included, though.

### CODE REVIEW

**Comment by maxtaco** [comment]
👍 Should I go ahead and merge it?

**Comment by zapu** [comment]
I can also add the compiled output of iced, or you can do it using the release script. Other than that, the merge itself is done :)

**Comment by zapu** [comment]
BTW I also have a branch with Travis CI enabled. I wanted to try it and was curious what was it all about. It pretty much just runs `icake3 test`, but it can do it on multiple different node versions. So this already shows some issues with node that was released about just a year ago.

https://travis-ci.org/zapu/coffeescript

It should be fairly easy to set this up on the main repo. I'm unsure whether you have to link your account to travis-ci.org or not - this is my biggest complaint, seems fairly invasive. I'd rather be told some webhook URLs to enter, instead of giving my entire account.

**Comment by maxtaco** [comment]
Super busy today but I managed to flip the switch on travis to turn on coffee-script repo

**Comment by zapu** [comment]
Thanks! Can you merge this one? Then I can make a PR with the travis config and some minor test fixes.

**Pull request merged**
