### PR TITLE
Merging mainline coffee

### PR DESCRIPTION
**Pull request by zapu**
Looks like I didn't squash the changes or something.

While the `export` change is not super important, the side effect is that our Travis CI tests now pass on all node versions.

Most notable changes:
- Fix operator precedence rules.
- Fix anonymous classes with 'export' keyword (should fix our tests on old node versions).
- Fixes for Node 7 warnings when async functions from standard library were called without callbacks (e.g. from 'fs' module).

Also I included compiled javascript files in this pull request, because the grammar has changed and I had some issues with it compiling itself, I had to use second iced package outside.

### CODE REVIEW

**Comment by maxtaco** [comment]
This looks great --- quick question, why doesn't travis seem to run on this PR?

**Comment by maxtaco** [comment]
@zapu this looks great.  I just want to make sure I get this right in terms of which merge strategy to use.  I was thinking that I'd do the standard "merge pull request" which will just keep all of the individual merges in the commit history.  Sound good?

**Comment by zapu** [comment]
Looks like last time (https://github.com/maxtaco/coffee-script/pull/194) I did a `git merge --squash` while working on the merge locally (there are always a few conflicts here and there). This wasn't the case a merge before though (https://github.com/maxtaco/coffee-script/pull/192).

~~Keeping individual commits keeps attribution of the code to original authors at a cost of less straight-forward commit history, but overall it sounds good to me, so go ahead :) Thanks!~~ (disregard, misunderstood git)

**Comment by zapu** [comment]
Thanks :)

**Comment by zapu** [comment]
Oh, looks like I got confused by the previous comment! I thought using the old merge PR option will somehow put all the commits into the tree. Nevermind, sorry!

**Pull request merged**
